name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Checkout repository code
        uses: actions/checkout@v2
      
      - 
        name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.10'
          architecture: 'x64'
          cache: 'pip'
      - 
        name: Install dependencies
        run: pip install -r test_requirements.txt
      
      - 
        name: Run test
        run: pytest

